features/cart/urls.py
from django.urls import path
from features.cart.views import my_cart, apply_coupon, update_cart_items


app_name = 'cart'
urlpatterns = [
    path('my_cart/', my_cart, name='my_cart'),
    path('apply_coupon/<str:coupon_code>', apply_coupon, name='apply_coupon'),
    path('update_cart_items/<int:product_id>/<int:quantity>/', update_cart_items, name='update_cart_items'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from features.store.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('features.account.urls')),
    path('cart/', include('features.cart.urls')),
    path('clothes/', include('features.clothes.urls')),
    path('store/', include('features.store.urls')),
    path('order/', include('features.order.urls')),
    path('payment/', include('features.payment.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    # URL pattern for serving media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # URL pattern for serving static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

features/cart/models.py
import decimal
from features.account.models import MyUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from features.clothes.models import Product


class Coupon(models.Model):
    """
    A coupon model that can be applied to a cart to get a discount.

    Attributes:
        code (str): The unique code of the coupon.
        amount (int): The amount of discount to be applied.
        percentage (int): The percentage of discount to be applied.
    """
    code = models.CharField(max_length=50, unique=True)
    amount = models.IntegerField(null=True, blank=True)
    percentage = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0), MaxValueValidator(100)])
    
    def __str__(self):
        return self.code


class UsedCoupon(models.Model):
    """
    A model that tracks used coupons for each customer.

    Attributes:
        customer (MyUser): The customer who used the coupon.
        coupon (Coupon): The coupon that was used.
        active (bool): Whether the coupon is still active or not.
    """
    customer = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)


class Cart(models.Model):
    """
    A model that represents a customer's shopping cart.

    Attributes:
        customer (MyUser): The customer who owns the cart.
        created (datetime): The datetime when the cart was created.
        updated (datetime): The datetime when the cart was last updated.
        total_price (Decimal): The total price of all items in the cart.
        customer_coupon (UsedCoupon): The coupon used by the customer, if any.
        discount (Decimal): The total discount applied to the cart.
        final_price (Decimal): The final price of the cart after applying the discount.
        checked_out (bool): Whether the cart has been checked out or not.

    Methods:
        update_total_price(): Update the total cart price based on the sum of all the cart items' 
            final prices.
        apply_coupon(): Applies the coupon discount to the cart total price based on the coupon 
            type (amount or percentage). Updates the cart discount and final price accordingly.
        save(): Overrides the default save method to update the final price of the cart based on 
            the discount applied.
    """
    customer = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    customer_coupon = models.ForeignKey(UsedCoupon, on_delete=models.SET_NULL, null=True, blank=True)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    final_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    checked_out = models.BooleanField(default=False)

    def update_total_price(self):
        self.total_price = sum(item.final_item_price for item in self.cart_items.all())
        if not self.total_price:
            self.customer_coupon = None
            self.discount = 0
        self.save()

    def apply_coupon(self):
        if self.customer_coupon.coupon.amount:
            self.discount = self.customer_coupon.coupon.amount
        if self.customer_coupon.coupon.percentage:
            self.discount = self.total_price * self.customer_coupon.coupon.percentage / 100
        self.update_total_price()

    def save(self, *args, **kwargs):
        if self.pk is not None:
            self.final_price = self.total_price - decimal.Decimal(str(self.discount))
        super(Cart, self).save(*args, **kwargs)

    def __str__(self):
        return self.customer.email


class CartItem(models.Model):
    """
    A model that represents an item added to a cart.

    Attributes:
        cart (Cart): The cart that the item belongs to.
        product (Product): The product that the item represents.
        quantity (int): The quantity of the product.
        final_item_price (Decimal): The final price of the item after any discounts have been applied.
        created (DateTimeField): The date and time that the item was created.
        updated (DateTimeField): The date and time that the item was last updated.
    """
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    final_item_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

features/cart/forms.py
from django import forms


class CouponApplyForm(forms.Form):
    """
    A form for applying coupon to cart. This form accepts coupon code.

    Attributes:
        code: CharField - The code given by user
    """
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Coupon Code'}))

features/cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect, render
from .models import (Cart, CartItem, Coupon, Product, UsedCoupon)
from .forms import CouponApplyForm


@login_required
def my_cart(request):
    """
    View function that displays the customer's cart with the ability to apply coupons to it.
    """
    # Retrieve or create the cart associated with the current customer.
    cart, created = Cart.objects.get_or_create(customer=request.user)

    # Retrieve all coupons and exclude those that have already been used by the customer
    coupons = Coupon.objects.all()
    unused_coupons = Coupon.objects.exclude(id__in=UsedCoupon.objects.filter(customer=request.user, active=False).values('coupon_id'))

    # Create a form to apply coupons to the cart
    form = CouponApplyForm(request.POST or None)
    
    if form.is_valid():
        # If form is valid extract the coupon code entered by the customer, retrieve a coupon with 
        # the entered code and check its validilty
        coupon_code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code=coupon_code)
            customer_coupon, created = UsedCoupon.objects.get_or_create(customer=request.user, coupon=coupon)
            if customer_coupon.active:
                cart.customer_coupon = customer_coupon
                cart.apply_coupon()
                messages.success(request, f"Coupon '{coupon_code}' applied successfully.")
            else:
                messages.error(request, f"Invalid coupon code '{coupon_code}'")
        except ObjectDoesNotExist:
            messages.error(request, f"Invalid coupon code '{coupon_code}'")
        return redirect('cart:my_cart')
    
    context = {'show_navbar_footer': True, 'cart': cart, 'unused_coupons': unused_coupons, 'coupon_form':form}
    return render(request, 'cart/cart.html', context)


@login_required
def update_cart_items(request, product_id, quantity):
    """
    View function that updates the quantity of a product in the customer's cart or removes it from the cart entirely.

    Args: product_id: The ID of the product being updated.
          quantity: The new quantity of the product being updated, or None if the product is being removed from the cart.
    """
    # Retrieve the cart for the current customer
    cart = get_object_or_404(Cart, customer=request.user)

    # Get the product by ID or raise Http404 error if not found
    product = get_object_or_404(Product, id=product_id)

    # Retrieve the cart item for the product, if it exists
    cart_item = CartItem.objects.filter(cart__customer=request.user, product=product).first()

    # If a cart item exists and a new quantity was specified, update the quantity and final item price
    # If quantity = 0, remove the cart item entirely
    if cart_item and quantity:
        cart_item.quantity = quantity
        cart_item.final_item_price = product.price * quantity
        cart_item.save()
    elif not quantity:
        cart_item.delete()

    # Update the total price of the cart
    cart.update_total_price()

    # If a coupon is applied to the cart, re-apply it after the cart item update
    if cart.customer_coupon:
        cart.apply_coupon()
        cart.save()

    return redirect('/cart/my_cart/')


@login_required
def apply_coupon(request, coupon_code):
    """
    Applies the given coupon to the customer's cart and redirects to the cart page.
    
    Args: coupon_code: str representing the code of the coupon to apply
    """
    # Retrieve the customer's cart
    cart = get_object_or_404(Cart, customer=request.user)

    # Retrieve the coupon with the given code and apply to the customer's cart
    coupon = get_object_or_404(Coupon, code=coupon_code)
    customer_coupon, created = UsedCoupon.objects.get_or_create(customer=request.user, coupon=coupon)
    cart.customer_coupon = customer_coupon
    cart.apply_coupon()
    messages.success(request, f"Coupon '{coupon}' applied successfully.")

    return redirect('/cart/my_cart/')

templates/cart/cart.html
{% extends 'base.html' %}

{% block title %} Cart
{% endblock %}

{% block content %}
    <div class="container w-50 mt-4">
        {% if cart.cart_items.all %}

            {% for item in cart.cart_items.all %}
                <div class="card shadow p-3 mb-4 bg-white rounded">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img class="border-primary" src="/media/{{ item.product.image }}"
                                style="object-fit: cover; width: 50%;">
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title">{{ item.product.name }}</h5>
                            <hr class="mt-2 mb-4">

                            <div class="row">
                                <div class="col-sm-3"> <h6 class="mb-0">Price :</h6> </div>
                                <div class="col-sm-9 text-secondary"> {{ item.product.price }} </div>
                            </div>
                            <hr class="my-2">

                            <div class="row">
                                <div class="col-sm-3"> <h6 class="mb-0">Quantity :</h6> </div>
                                <div class="col-sm-1">
                                    {% if item.quantity > 1 %}
                                        <button type="button" class="btn btn-primary"
                                            onclick="location.href='{% url 'cart:update_cart_items' product_id=item.product.id quantity=item.quantity|add:-1 %}'"
                                            style="display: flex; justify-content: center; width: 30px; height: 30px; line-height: 15px; border-radius: 50%; font-weight: bold;">-</button>
                                    {% else %}
                                        <button type="button" class="btn btn-primary"
                                            onclick="location.href='{% url 'cart:update_cart_items' product_id=item.product.id quantity=0 %}'"
                                            style="display: flex; justify-content: center; width: 30px; height: 30px; line-height: 15px; border-radius: 50%; font-weight: bold;">-</button>
                                    {% endif %}
                                </div>
                                <div class="col-sm-1 text-secondary text-center"> {{ item.quantity }} </div>
                                <div class="col-sm-1 text-center">
                                    <button type="button" class="btn btn-primary"
                                        onclick="location.href='{% url 'cart:update_cart_items' product_id=item.product.id quantity=item.quantity|add:1 %}'"
                                        style="display: flex; justify-content: center; width: 30px; height: 30px; line-height: 15px; border-radius: 50%; font-weight: bold;">+</button>
                                </div>
                            </div>
                            <hr class="my-2">

                            <div class="row">
                                <div class="col-sm-3"> <h6 class="mb-0">Total Price :</h6> </div>
                                <div class="col-sm-9 text-secondary"> {{ item.final_item_price }} </div>
                            </div>
                            <hr class="my-2">

                            <div class="d-flex mt-4">
                                <button type="submit" class="btn btn-danger"
                                    onclick="location.href='{% url 'cart:update_cart_items' product_id=item.product.id quantity=0 %}'">Remove</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="text-center mb-5">
                <h4> Total cart price: {{ cart.total_price }} </h4>
            </div>

            {% if unused_coupons %}
                <div class="row justify-content-center mb-3">
                    <div class="col-sm-2 m-3"> <p class="mt-4">Select Coupon:</p> </div>
                    {% for coupon in unused_coupons %}
                        <div class="col-sm-2 p-0 m-3">
                            <div class="card align-items-center">
                                <a class="card-flex stretched-link text-decoration-none"
                                    href="{% url 'cart:apply_coupon' coupon.code%}">
                                    <div class="card-body text-center p-1">
                                        <h5 class="card-title">{{ coupon.code }}</h5>
                                        {% if coupon.amount %}
                                            <p class="card-text">Rs. {{ coupon.amount }} off</p>
                                        {% else %}
                                            <p class="card-text">{{ coupon.percentage }}% off</p>
                                        {% endif %}
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="row d-flex align-items-center justify-content-center">
                <div class="col-md-3" style="text-align: right;">Have coupon code?</div>
                <div class="col-md-3">
                    <form method="POST" action="{% url 'cart:my_cart' %}">
                        {% csrf_token %}
                        <div class="form-group"> {{ coupon_form.code }} </div>
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary btn-block">Apply</button>
                    </form>
                </div>
            </div>

            <div class="text-center mt-5"> <h4> Final cart price: {{ cart.final_price }} </h4> </div>

            <div class="d-flex justify-content-center mt-4">
                <button type="submit" class="btn btn-primary" onclick="location.href='/payment/checkout_cart/'">Checkout</button>
            </div>

        {% else %}

            <div class="text-center"> <strong> No items in your cart! </strong> </div>

        {% endif %}

        <div class="container text-center my-5">
            {% for message in messages %}
                <strong> {{ message }} </strong><br>
            {% endfor %}
        </div>
    </div>
{% endblock %}