features/clothes/urls.py
from django.urls import path
from features.clothes.views import product_detail, add_product, view_products, update_product, delete_product


app_name = 'clothes'
urlpatterns = [
    path('product_detail/<int:product_id>', product_detail, name='product_detail'),    
    path('add_product/', add_product, name='add_product'),
    path('view_products/', view_products, name='view_products'),
    path('update_product/<int:product_id>', update_product, name='update_product'),
    path('delete_product/<int:product_id>', delete_product, name='delete_product'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from features.store.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('features.account.urls')),
    path('cart/', include('features.cart.urls')),
    path('clothes/', include('features.clothes.urls')),
    path('store/', include('features.store.urls')),
    path('order/', include('features.order.urls')),
    path('payment/', include('features.payment.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    # URL pattern for serving media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # URL pattern for serving static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
      {% block title %}
      {% endblock %}
    </title>

    {% load static %}
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/custom.css' %}" rel="stylesheet"/>
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.png">
  </head>

  <body>

    {% if show_navbar_footer %}
      <header class="header">
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
            {% if request.user.user_type == "Merchant" %}
            <a class="navbar-brand" href="/store/dashboard/">Store</a>
            {% else %}
            <a class="navbar-brand" href="/">Store</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

              {% if request.user.user_type == "Merchant" %}
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/store/dashboard/' %}active{% endif %}"
                    href="/store/dashboard">Dashboard</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/clothes/add_product/' %}active{% endif %}"
                    href="/clothes/add_product">Add Product</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/clothes/view_products/' or '/clothes/product_detail/' in request.path or '/clothes/update_product/' in request.path or '/clothes/delete_product/' in request.path %}active{% endif %}"
                    href="/clothes/view_products">View Products</a>
                </li>
              </ul>

              {% elif request.user.user_type == "Customer" %}
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/' %}active{% endif %}"
                    href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/order/my_order/' or '/order/order_summary/' in request.path %}active{% endif %}"
                    href="/order/my_order">Orders</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/cart/my_cart/' %}active{% endif %}"
                    href="/cart/my_cart">Cart</a>
                </li>

              </ul>
              {% endif %}

              <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/account/profile/' or '/account/update_profile/' in request.path %}active{% endif %}"
                    href="/account/profile">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/account/logout">Logout</a>
                </li>

                {% else %}

                <li class="nav-item">
                  <a class="nav-link" href="/account/login">Login</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="/account/signup">Sign Up</a>
                </li>

                {% endif %}
              </ul>

            </div>
          </div>
        </nav>
      </header>
    {% endif %}

    <main class="main-content">
      {% block content %}
      {% endblock %}
    </main>

    {% if show_navbar_footer %}
      <footer class="footer">
        <div class="footer-items">
          <a href="#">About Us</a>
          <a href="#">Contact Us</a>
        </div>
        <p>Copyright &copy; <span id="year"></span> Khushi Kamat | All Rights Reserved</p>
      </footer>
    {% endif %}

    {% block jsextra %}
    {% endblock %}

    <script>
      var currentYear = new Date().getFullYear();
      document.getElementById("year").textContent = currentYear;
    </script>
    
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block title %} Dashboard
{% endblock %}

{% block content %}
    <div class="container text-center mt-5">
        {% for message in messages %}
            <strong> {{ message }} </strong> <br>
        {% endfor %}
    </div>

{% comment %} {% if user.is_authenticated %}
<div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    <strong>Welcome {{ user.name }} </strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %} {% endcomment %}

{% comment %} <div class="container-fluid px-0 mb-3">
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static '/images/img1.jpg' %}" class="d-block w-100" alt="..." height="650">
            </div>
            <div class="carousel-item">
                <img src="{% static '/images/img2.jpg' %}" class="d-block w-100" alt="..." height="650">
            </div>
            <div class="carousel-item">
                <img src="{% static '/images/img3.jpg' %}" class="d-block w-100" alt="..." height="650">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div> {% endcomment %}

{% comment %} <h2 class="text-center">Me at a glance</h2>

<div class="my-3 d-flex justify-content-center">
    <div class="row">
        <div class="col-md-4 px-5">
            <div class="card text-bg-primary" style="width: 18rem;">
                <img src="{% static '/images/card_img.jpg' %}" class="card-img-top" alt="..." height="200">
                <div class="card-body" align="center">
                    <h5 class="card-title">Python Developer</h5>
                    <p class="card-text">Developed projects using Flask and Django frameworks.</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 px-5">
            <div class="card text-bg-primary" style="width: 18rem;">
                <img src="{% static '/images/card_img.jpg' %}" class="card-img-top" alt="..." height="200">
                <div class="card-body" align="center">
                    <h5 class="card-title">AI Developer</h5>
                    <p class="card-text">Developed Supervised and Unsupervised ML models.</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 px-5">
            <div class="card text-bg-primary" style="width: 18rem;">
                <img src="{% static '/images/card_img.jpg' %}" class="card-img-top" alt="..." height="200">
                <div class="card-body" align="center">
                    <h5 class="card-title">Designer</h5>
                    <p class="card-text">Designed web pages for projects using HTML and CSS.</p>
                </div>
            </div>
        </div>
    </div>
</div> {% endcomment %}

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %} Home
{% endblock %}

{% block content %}
    <div class="container text-center mt-4">
        {% for message in messages %}
            <strong> {{ message }} </strong> <br>
        {% endfor %}
    </div>

    <div class="row mx-4 my-4">
        {% for product in product_list %}
            <div class="col-md-2 mb-4">
                <div class="card">
                    <div class="card" style="border: none;">
                        <a class="card-block stretched-link text-decoration-none"
                            href="{% url 'clothes:product_detail' product.id %}">
                            <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.title }}"
                                style="object-fit: cover; height: 200px;">
                            <div class="card-body text-center">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.price }}</p>
                            </div>
                        </a>
                    </div>
                    <div class="text-center my-3">
                        <div class="btn-group">
                            <div class="mx-3">
                                <button type="submit" class="btn btn-primary"
                                    onclick="location.href='/store/add_to_cart/{{product.id}}'">Add to cart</button>
                            </div>
                            <div class="mx-3">
                                <button type="submit" class="btn btn-primary"
                                    onclick="location.href='/store/buy_now/{{product.id}}'">Buy Now</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}