features/order/urls.py
from django.urls import path
from features.order.views import my_order, order_operations, generate_pdf, order_operations


app_name = 'order'
urlpatterns = [
    path('my_order/', my_order, name='my_order'),
    path('order_summary/<int:order_id>/', order_operations, name='order_summary'),
    path('cancel_order/<int:order_id>/', order_operations, name='cancel_order'),
    path('generate_pdf/<int:order_id>/', generate_pdf, name='generate_pdf'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from features.store.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('features.account.urls')),
    path('cart/', include('features.cart.urls')),
    path('clothes/', include('features.clothes.urls')),
    path('store/', include('features.store.urls')),
    path('order/', include('features.order.urls')),
    path('payment/', include('features.payment.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    # URL pattern for serving media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # URL pattern for serving static files during development
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)      

features/order/models.py
from features.account.models import MyUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Order(models.Model):
    """
    A model that represents an order that has been placed.

    Attributes:
        cart (Cart): The cart that the order was created from.
        customer (MyUser): The customer who placed the order.
        billing_address (str): The billing address for the order.
        contact (PhoneNumberField): The contact phone number for the order.
        items (ManyToManyField): The products that are part of the order, through OrderItem.
        total_price (Decimal): The total price of the order before any discounts have been applied.
        coupon (Coupon): The coupon that was applied to the order, if any.
        discount (Decimal): The amount of the discount applied to the order.
        final_price (Decimal): The final price of the order after any discounts have been applied.
        created (DateTimeField): The date and time that the order was created.
        updated (DateTimeField): The date and time that the order was last updated.
        status (bool): The status of the order.
        is_paid (bool): Whether the order has been paid for.
    """
    cart = models.ForeignKey("cart.Cart", on_delete=models.SET_NULL, null=True, blank=True)
    customer = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    billing_address = models.CharField(max_length=150, null=True, blank=True)
    contact = PhoneNumberField(null=True, blank=True)
    items = models.ManyToManyField("clothes.Product", through='OrderItem', related_name='orders')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    coupon = models.ForeignKey("cart.Coupon", on_delete=models.SET_NULL, null=True, blank=True)
    discount = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    final_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
    is_paid = models.BooleanField(default=False)
    
    def __str__(self):
        return self.customer.email


class OrderItem(models.Model):
    """
    A model that represents an item in an order.

    Attributes:
        order (Order): The order that the item belongs to.
        product (Product): The product that the item represents.
        quantity (int): The quantity of the product.
        final_item_price (Decimal): The final price of the item after any discounts have been applied.
    """
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey("clothes.Product", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    final_item_price = models.DecimalField(max_digits=10, decimal_places=2, null=False)

features/order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from weasyprint import HTML
from .models import (Order)


@login_required
def my_order(request):
    """
    View to display the orders made by the customer.
    """
    # Get all active orders made by the customer
    active_orders = Order.objects.filter(customer=request.user, status=True)

    # Get all cancelled orders made by the customer
    cancelled_orders = Order.objects.filter(customer=request.user, status=False)

    context = {'show_navbar_footer': True, "active_orders": active_orders, "cancelled_orders": cancelled_orders}
    return render(request, 'order/my_order.html', context)


@login_required
def order_operations(request, order_id):
    """
    Handles various operations related to orders like displaying order summary and cancelling orders.

    Args: order_id: The ID of the order to perform the operation on.
    """
    # Get the order for the given id and check if it belongs to the current customer
    order = Order.objects.get(customer=request.user, id=order_id)

    # If the URL contains 'order_summary', render the order summary page and if the URL contains 
    # 'cancel_order' and the order is not already cancelled, cancel the order
    if 'order_summary' in request.path_info:
        context = {'show_navbar_footer': True, "order": order, "show_print_button": True}
        return render(request, 'order/order_summary.html', context)
    elif 'cancel_order' in request.path_info:
        if order.status:
            order.status = False
            order.save()
            messages.success(request, f"Order Cancelled")
    
    return redirect('/order/my_order/')


@login_required
def generate_pdf(request, order_id):
    """
    This function generates a PDF of the order summary for the given order ID.
    
    Args: order_id: ID of the order to generate the PDF for.
    """
    # Get the order object for the given order ID and generate HTML string for the order object
    order = Order.objects.get(customer=request.user.id, id=order_id)
    html = render_to_string('order/order_summary.html', {'order': order, "show_print_button": False})

    # Create an HttpResponse object with PDF content type and set filename
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="order_summary_{}.pdf"'.format(order_id)

    # Use WeasyPrint to generate PDF file from the HTML string and write to response object
    HTML(string=html).write_pdf(response)

    return response

templates/order/my_order.html
{% extends 'base.html' %}

{% block title %} My Orders
{% endblock %}

{% block content %}
    <div class="container text-center my-4">
        {% for message in messages %}
            <strong> {{ message }} </strong><br>
        {% endfor %}
    </div>

    <div class="container w-50">
        {% if active_orders or cancelled_orders %}

            {% if active_orders %}
                <h3 class="my-3 text-center">Active Orders</h3>
                {% for order in active_orders %}
                    <div class="card shadow p-3 mb-4 bg-white rounded">
                        {% for item in order.orderitem_set.all %}

                            <div class="card my-2" style="border: none;">
                                <div class="row no-gutters">
                                    <div class="col-md-4 text-center">
                                        <img class="border-primary" src="/media/{{ item.product.image }}"
                                            style="object-fit: cover; width: 50%;">
                                    </div>
                                    <div class="col-md-8">
                                        <h5 class="card-title">{{ item.product.name }}</h5>
                                        <hr class="mt-2 mb-4">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <h6 class="mb-0">Price :</h6>
                                            </div>
                                            <div class="col-sm-9 text-secondary">
                                                {{ item.product.price }}
                                            </div>
                                        </div>
                                        <hr class="my-2">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <h6 class="mb-0">Quantity :</h6>
                                            </div>
                                            <div class="col-sm-9 text-secondary">
                                                {{ item.quantity }}
                                            </div>
                                        </div>
                                        <hr class="my-2">
                                        <div class="row">
                                            <div class="col-sm-3">
                                                <h6 class="mb-0">Total Price :</h6>
                                            </div>
                                            <div class="col-sm-9 text-secondary">
                                                {{ item.final_item_price }}
                                            </div>
                                        </div>
                                        <hr class="my-2">
                                    </div>
                                </div>
                            </div>

                        {% endfor %}

                        <div class="row no-gutters mt-3">
                            <div class="col-md-4">
                                <h6>Total order price: {{ order.total_price }}</h6>
                                {% if order.discount %}
                                    <h6>Coupon: {{ order.coupon }}</h6>
                                    <h6>Discount: {{ order.discount }}</h6>
                                    <h6>Final order price: {{ order.final_price }}</h6>
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <h5>Shipping Details:</h5>
                                <h6>Billing Address: {{ order.billing_address }}</h6>
                                <h6>Contact: {{ order.contact }}</h6>
                            </div>
                        </div>

                        <div class="text-center">
                            <div class="btn-group mt-3">
                                <div class="mx-3">
                                    <button type="submit" class="btn btn-primary"
                                        onclick="location.href='{% url 'order:order_summary' order.id %}'">Order Summary</button>
                                </div>
                                <div class="mx-3">
                                    <button type="submit" class="btn btn-danger"
                                        onclick="location.href='{% url 'order:cancel_order' order.id %}'">Cancel Order</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        
            {% if cancelled_orders %}
                <h3 class="my-3 text-center">Cancelled Orders</h3>
                {% for order in cancelled_orders %}
                    <div class="card shadow p-3 mb-4 bg-white rounded">
                        {% for item in order.orderitem_set.all %}
                            <div class="card my-2" style="border: none;">
                                <div class="row no-gutters">
                                    <div class="col-md-4 text-center">
                                        <img class="border-primary" src="/media/{{ item.product.image }}"
                                            style="object-fit: cover; width: 50%;">
                                    </div>
                                    <div class="col-md-8">
                                        <h5 class="card-title">{{ item.product.name }}</h5>
                                        <hr class="mt-2 mb-4">

                                        <div class="row">
                                            <div class="col-sm-3">
                                                <h6 class="mb-0">Price :</h6>
                                            </div>
                                            <div class="col-sm-9 text-secondary"> {{ item.product.price }} </div>
                                        </div>
                                        <hr class="my-2">

                                        <div class="row">
                                            <div class="col-sm-3"> <h6 class="mb-0">Quantity :</h6> </div>
                                            <div class="col-sm-9 text-secondary"> {{ item.quantity }} </div>
                                        </div>
                                        <hr class="my-2">

                                        <div class="row">
                                            <div class="col-sm-3"> <h6 class="mb-0">Total Price :</h6> </div>
                                            <div class="col-sm-9 text-secondary"> {{ item.final_item_price }} </div>
                                        </div>
                                        <hr class="my-2">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="row no-gutters mt-3">
                            <div class="col-md-4">
                                <h6>Total order price: {{ order.total_price }}</h6>
                                {% if order.discount %}
                                    <h6>Coupon: {{ order.coupon }}</h6>
                                    <h6>Discount: {{ order.discount }}</h6>
                                    <h6>Final order price: {{ order.final_price }}</h6>
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <h5>Shipping Details:</h5>
                                <h6>Billing Address: {{ order.billing_address }}</h6>
                                <h6>Contact: {{ order.contact }}</h6>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

        {% else %}

            <div class="text-center">
                <strong> No orders available! </strong>
            </div>

        {% endif %}
    </div>
{% endblock %}

templates/order/order_summary.html
{% extends 'base.html' %}

{% block title %} Order Summary
{% endblock %}

{% block content %}
    <div class="container w-50 mt-3">
        <h3 class="my-3 text-center">Order Summary</h3>

        <div class="card shadow p-3 mb-4 bg-white rounded">
            {% for item in order.orderitem_set.all %}
                <div class="card my-2" style="border: none;">
                    <div class="row no-gutters">
                        <div class="col-md-4 text-center">
                            <img class="border-primary" src="http://127.0.0.1:8000{{item.product.image.url}}" style="object-fit: cover; width: 25%;">
                        </div>
                        <div class="col-md-8">
                            <h5 class="card-title">{{ item.product.name }}</h5>                    
                            <div class="row">
                                <div class="col-sm-9 text-secondary"> x {{ item.quantity }} </div>
                                <div class="col-sm-3"> {{ item.final_item_price }} </div>
                            </div>
                            <hr class="my-2">
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="row no-gutters mt-3">
                <div class="col-md-4">
                    <h6>Total order price: {{ order.total_price }}</h6>
                    {% if order.discount %}
                        <h6>Coupon: {{ order.coupon }}</h6>
                        <h6>Discount: {{ order.discount }}</h6>
                        <h6>Final order price: {{ order.final_price }}</h6>
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <h5>Shipping Details:</h5>
                    <h6>Billing Address: {{ order.billing_address }}</h6>
                    <h6>Contact: {{ order.contact }}</h6>
                </div>
            </div>

            {% if show_print_button %}
                <div class="d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-primary" onclick="location.href='{% url 'order:generate_pdf' order.id %}'">Print</button>
                </div>
            {% endif %}
        </div>  
        
        <div class="container text-center mt-5">
            {% for message in messages %}
                <strong> {{ message }} </strong><br>
            {% endfor %}
        </div>
    </div>
{% endblock %}